StylesPath = styles
LanguageNames = English, German

# 1. Alles im excerpts-Ordner ist Englisch
[excerpts/*.md]
BasedOnStyles = Vale, excerpts
Language = English

# 2. Alles andere (Root, Präsentation etc.) ist Deutsch
[*.md]
BasedOnStyles = Vale, excerpts
Language = German
